# ~/.psmux.conf

# Prefix
unbind C-b
set -g prefix `
bind ` send-prefix

# Vi mode
setw -g mode-keys vi

# Terminal
set -g default-terminal "tmux-256color"

# Timing and Focus
set -sg escape-time 0
set -g focus-events on

# Window and Pane Indices
set -g base-index 1
setw -g pane-base-index 1

# Clock Mode
setw -g clock-mode-style 24

# History
set -g history-limit 10000

# Clipboard integration
set -s set-clipboard external

# Fix Neovim colors
set -sg terminal-overrides ",*:RGB"

# Cleaner panes separator
set -g pane-border-lines simple

# Increase repeat time to send multiple commands a time
set -sg repeat-time 1000

# Last window
bind h last-window

# Open new windows and panes in cwd
bind c new-window -c "#{pane_current_path}"
bind l split-window -h -c "#{pane_current_path}"
bind j split-window -v -c "#{pane_current_path}"

# Ctrl-Shift vim keys to switch windows
bind -n C-S-h previous-window
bind -n C-S-l next-window

# Status bar on top
set -g status-position top

# Send prefix to nested session
bind-key -n C-a send-prefix

# TPM Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'Morantron/tmux-fingers'
set -g @plugin 'omerxx/tmux-floax'
set -g @plugin 'catppuccin/tmux'

# Plugin Configurations

# tmux-fingers
# Match URLs
bind U run -b "#{@fingers-cli} start #{pane_id} --patterns url"
# Match SHA256 hashes
set -g @fingers-pattern-sha256 "sha256-[a-zA-Z0-9+/]{43}="
bind H run -b "#{@fingers-cli} start #{pane_id} --patterns sha256"
# Edit file using nvim in a new tmux window
bind E run -b "#{@fingers-cli} start #{pane_id} --patterns path --main-action 'xargs tmux new-window nvim'"
# Target adjacent panes
bind -n M-h run -b "#{@fingers-cli} start {left-of}"
bind -n M-j run -b "#{@fingers-cli} start {down-of}"
bind -n M-k run -b "#{@fingers-cli} start {up-of}"
bind -n M-l run -b "#{@fingers-cli} start {right-of}"
bind -n M-o run -b "#{@fingers-cli} start {last}"

# tmux-floax
set -g @floax-bind 'k'
set -g @floax-width '90%'
set -g @floax-height '90%'

# catppuccin
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
